### ISSUE TITLE
Ublox MAX M8 model does not line up with pcb

### ISSUE THREAD

**Issue by jskorepa** [cvra/kicad-lib#2]
What am I doing wrong? 
![screenshot 1](https://cloud.githubusercontent.com/assets/21140749/20159096/d4c56d3a-a6de-11e6-8701-c347fa949957.png)
![screenshot 2](https://cloud.githubusercontent.com/assets/21140749/20159095/d4c4f86e-a6de-11e6-9846-03dbbbdcfafc.png)

**Comment by msplr** [comment]
I think it's a problem of metric vs imperial units used in the 3D model and in KiCad's 3D viewer.

At the moment I don't know if the model is wrong or if the 3D viewer doesn't distinguish between units.

A workaround would be to set a scale factor to convert the units. You can set the scale factor under "3D settings" in the "Footprint Properties" of the ublox footprint.
Try something like 0.254 (imperial-> metric) or 0.393701 (metric -> imperial).

**Comment by jskorepa** [comment]
Thank you for your fast response. It is indeed the case. Now it has wrong offset, i can guess it, but do you know a way to calculate it?
![snimek z 2016-11-10 01-37-04](https://cloud.githubusercontent.com/assets/21140749/20160300/381de73e-a6e6-11e6-8355-8e437d5630be.png)

**Comment by msplr** [comment]
Probably the origins aren't the same.

Open the footprint in the editor to find the offset of the origin. The 3D model's origin is probably right in the center.
